/* 
**  mod_conflearn.c -- Apache sample conflearn module
**  [Autogenerated via ``apxs -n conflearn -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_conflearn.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /conflearn in as follows:
**
**    #   httpd.conf
**    LoadModule conflearn_module modules/mod_conflearn.so
**    <Location /conflearn>
**    SetHandler conflearn
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /conflearn and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/conflearn 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_conflearn.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"


typedef struct {
	int enabled;		/* Enable or disable our module */
	const char *path;	/* Some path to...something */
	int type_of_action;	/* 1 means action A, 2 means action B and so on */
} example_config;

example_config config;

/* The sample content handler */
static int conflearn_handler(request_rec *r)
{
    if (!r->handler || strcmp(r->handler, "conflearn")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

	ap_set_content_type(r, "text/plain");
	
    ap_rprintf(r, "Enabled: %u\n", config.enabled);
    ap_rprintf(r, "Path: %s\n", config.path);
    ap_rprintf(r, "TypeOfAction: %x\n", config.type_of_action);
    return OK;
}

static void conflearn_register_hooks(apr_pool_t *p)
{
	config.enabled = 1;
    config.path = "/foo/bar";
    config.type_of_action = 0x00;
    ap_hook_handler(conflearn_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Handler for the "exampleEnabled" directive */
const char *example_set_enabled(cmd_parms *cmd, void *cfg, const char *arg)
{
    if(!strcasecmp(arg, "on")) config.enabled = 1;
    else config.enabled = 0;
    return NULL;
}

/* Handler for the "examplePath" directive */
const char *example_set_path(cmd_parms *cmd, void *cfg, const char *arg)
{
    config.path = arg;
    return NULL;
}

/* Handler for the "exampleAction" directive */
/* Let's pretend this one takes one argument (file or db), and a second (deny or allow), */
/* and we store it in a bit-wise manner. */
const char *example_set_action(cmd_parms *cmd, void *cfg, const char *arg1, const char *arg2)
{
    if(!strcasecmp(arg1, "file")) config.type_of_action = 0x01;
    else config.type_of_action = 0x02;
    
    if(!strcasecmp(arg2, "deny")) config.type_of_action += 0x10;
    else config.type_of_action += 0x20;
    return NULL;
}



static const command_rec        example_directives[] =
{
    AP_INIT_TAKE1("exampleEnabled", example_set_enabled, NULL, RSRC_CONF, "Enable or disable mod_example"),
    AP_INIT_TAKE1("examplePath", example_set_path, NULL, RSRC_CONF, "The path to whatever"),
    AP_INIT_TAKE2("exampleAction", example_set_action, NULL, RSRC_CONF, "Special action value!"),
    { NULL }
};


/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA conflearn_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    example_directives,                 /* Any directives we may have for httpd */
    conflearn_register_hooks  /* register hooks                      */
};

